import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function POST(request: Request) {
    try {
        const body = await request.json();
        const { name, domain, hrms_provider } = body;

        if (!name || !domain || !hrms_provider) {
            return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
        }

        // Check if domain already exists
        const existing = await prisma.corporatePartner.findUnique({
            where: { domain },
        });

        if (existing) {
            return NextResponse.json({ error: 'Domain already registered' }, { status: 400 });
        }

        const partner = await prisma.corporatePartner.create({
            data: {
                name,
                domain,
                hrms_provider,
                // api_key and webhook_secret auto-generated by default
            },
        });

        return NextResponse.json(partner, { status: 201 });
    } catch (error) {
        console.error('Error registering partner:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
